nodeLinker: pnp

npmAuthToken: '${NODE_AUTH_TOKEN-}'

npmPublishRegistry: '${NODE_PUBLISH_REGISTRY-}'

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
      spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.2.3.cjs
