version: '3'

services:
    unblockneteasemusic:
        build: .
        environment:
            NODE_ENV: production

        # Change sources here
        # command: ["-o", "bilibili", "kugou", "kuwo", "ytdlp"]

        ports:
            - ${HTTP_PROXY_PORT:-8080}:8080
            - ${HTTPS_PROXY_PORT:-8081}:8081
