version: '3'

services:
    unblockneteasemusic:
        build: .
        environment:
            NODE_ENV: production

        # Change sources here
        # command: ["-o", "bilibili", "kugou", "kuwo", "ytdlp"]

        ports:
            - ${HTTP_PROXY_PORT:-80}:80
            - ${HTTPS_PROXY_PORT:-443}:443
