name: Test the sources availability with Jest

on:
    push:
        branches:
            - 'enhanced'
        paths-ignore:
            - '**.md'

    pull_request:
        types: [opened, synchronize, reopened]
        paths-ignore:
            - '**.md'

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    test-sources:
        runs-on: ubuntu-latest
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node.js 14
              uses: actions/setup-node@v2
              with:
                  node-version: 14
                  cache: yarn

            - name: Install dependencies
              run: yarn

            - name: Test the sources with Jest
              run: yarn test
